import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mfreyre' at '8/6/15 1:24 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/6/15 1:24 PM
 */
public class BoardTest {
    @Test public void testSomeLibraryMethod() {
        Board classUnderTest = new Board();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
