import javax.swing.text.Position;
import java.io.PrintStream;
import java.util.HashMap;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mfreyre' at '8/6/15 1:24 PM' with Gradle 2.5
 *
 * @author mfreyre, @date 8/6/15 1:24 PM
 */
public class Board {
    private final PrintStream printStream;
    private HashMap<String, String> positionsMap = new HashMap();


//    private Positions position1;
//    private Positions position2;
//    private Positions position3;
//    private Positions position4;
//    private Positions position5;
//    private Positions position6;
//    private Positions position7;
//    private Positions position8;
//    private Positions position9;

    public Board(PrintStream printStream) {
        this.printStream = printStream;
//        this.position1 = new Positions();
//        this.position2 = new Positions();
//        this.position3 = new Positions();
//        this.position4 = new Positions();
//        this.position5 = new Positions();
//        this.position6 = new Positions();
//        this.position7 = new Positions();
//        this.position8 = new Positions();
//        this.position9 = new Positions();
        positionsMap.put("1", "    ");
        positionsMap.put("2", "    ");
        positionsMap.put("3", "    ");
        positionsMap.put("4", "    ");
        positionsMap.put("5", "    ");
        positionsMap.put("6", "    ");
        positionsMap.put("7", "    ");
        positionsMap.put("8", "    ");
        positionsMap.put("9", "    ");

    }


    public void displayBoard() {
        printStream.println(positionsMap.get("1") + "|" + positionsMap.get("2") + "|" + positionsMap.get("3"));
        printStream.println(" -------------");
        printStream.println(positionsMap.get("4") + "|" + positionsMap.get("5") + "|" + positionsMap.get("6"));
        printStream.println(" -------------");
        printStream.println(positionsMap.get("7") + "|" + positionsMap.get("8") + "|" + positionsMap.get("9"));

    }

    public void setPositionToSymbol(String positionNum, String symbol) {
        positionsMap.put(positionNum, "  " + symbol + "  ");

    }

}

